# Generated by Django 4.1.4 on 2022-12-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='Название города')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('map_coordinates', models.CharField(max_length=255, verbose_name='Координаты на карте')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('text', models.CharField(max_length=500, verbose_name='Текст отзыва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
        ),
    ]
